### ISSUE TITLE
integer divide by zero in evaluateArithmeticExpression

### ISSUE THREAD

**Issue by jo-me** [woven-planet/go-zserio#109]
Hi,

when generating code based on zs files of v2.10 or v2.11 we often see errors like the one below that unfortunately contains no hint as of where it is happening. 

```
...
2023/07/24 13:46:00 Parsing file zs/road/reference/types.zs...
2023/07/24 13:46:00 Parsing file zs/road/road.zs...
2023/07/24 13:46:00 Parsing file zs/system/_module.zs...
2023/07/24 13:46:00 Parsing file zs/system/types.zs...
panic: runtime error: integer divide by zero

goroutine 1 [running]:
github.com/woven-planet/go-zserio/internal/ast.(*Expression).evaluateArithmeticExpression(0xc0003c8a80?)
        /home/jochen/go/pkg/mod/github.com/woven-planet/go-zserio@v0.6.2/internal/ast/expression.go:457 +0x44a
github.com/woven-planet/go-zserio/internal/ast.(*Expression).Evaluate(0xc0003c9c00, 0xc000349e30?)
        /home/jochen/go/pkg/mod/github.com/woven-planet/go-zserio@v0.6.2/internal/ast/expression.go:714 +0x26f
github.com/woven-planet/go-zserio/internal/ast.(*Struct).Evaluate(0xc0003dfd00, 0xc0003f26e0)
        /home/jochen/go/pkg/mod/github.com/woven-planet/go-zserio@v0.6.2/internal/ast/struct.go:50 +0x150
github.com/woven-planet/go-zserio/internal/model.(*Model).EvaluateStructs(0xc0002cdd08?)
        /home/jochen/go/pkg/mod/github.com/woven-planet/go-zserio@v0.6.2/internal/model/transform.go:174 +0x105
github.com/woven-planet/go-zserio/internal/model.(*Model).evaluate(0xc0002cdd08)
        /home/jochen/go/pkg/mod/github.com/woven-planet/go-zserio@v0.6.2/internal/model/model.go:131 +0x370
github.com/woven-planet/go-zserio/internal/model.FromFiles({0xc00030ce00, 0x19, 0x8000104?})
        /home/jochen/go/pkg/mod/github.com/woven-planet/go-zserio@v0.6.2/internal/model/model.go:33 +0xbf
github.com/woven-planet/go-zserio/internal/model.FromFilesystem({0xc000248310?, 0x5538ac?, 0xc00037a0a0?})
        /home/jochen/go/pkg/mod/github.com/woven-planet/go-zserio@v0.6.2/internal/model/model.go:54 +0x56
github.com/woven-planet/go-zserio/internal/cli.glob..func1(0xe0e580?, {0xc000248310?, 0x7?, 0x7?})
        /home/jochen/go/pkg/mod/github.com/woven-planet/go-zserio@v0.6.2/internal/cli/generate.go:28 +0x3c
github.com/spf13/cobra.(*Command).execute(0xe0e580, {0xc0002482a0, 0x7, 0x7})
        /home/jochen/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xe0e800)
        /home/jochen/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/jochen/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/woven-planet/go-zserio/internal/cli.Execute()
        /home/jochen/go/pkg/mod/github.com/woven-planet/go-zserio@v0.6.2/internal/cli/root.go:15 +0x25
main.main()
        /home/jochen/go/pkg/mod/github.com/woven-planet/go-zserio@v0.6.2/cmd/go-zserio/main.go:8 +0x17
```
 
It would be good to have some context when an error occurs.

Thanks

Jochen Mehlhorn <jochen.mehlhorn@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH

[Provider Information](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by Danaozhong** [comment]
@jo-me Thank you for the problem report!

Indeed, intuitive error reporting is something we should add to our To-Do list.
I assume (just guessing) that the error originates from `evaluateArithmeticExpression()`, which assumes that the values stored inside `expr.OperandX.ResultIntValue` are always set as hard-coded constants. In some cases, we have no actual hard-coded value, and it would not make any sense to actually run calculations.

Let me debug this next week and come back to you.

**Comment by Danaozhong** [comment]
This issue should be fixed with https://github.com/woven-planet/go-zserio/pull/113. @jo-me Could you please confirm, once convenient for you? Thanks!

**Comment by jo-me** [comment]
Thanks @Danaozhong , with the latest version on main branch, I do not see any of these errors during code generation anymore
